version: '2.0'

services:
  base: &base
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: dev.env
    pid: host
    working_dir: /src
    depends_on:
      - db
    volumes:
      - .:/src
      - bundle:/usr/local/bundle
      - node_modules:/src/node_modules

  ui:
    <<: *base
    ports:
      - "3000:3000"
    command: /bin/sh -c './bin/update && bundle exec ./bin/rails s'
    environment:
      SETTINGS__BACKEND__URL: http://app.aida.lvh.me/
      SETTINGS__BACKEND__PUBLIC_SOCKET_URL: ws://app.aida.lvh.me/socket
      SETTINGS__BACKEND__PUBLIC_CONTENT_URL: http://app.aida.lvh.me/content
      SETTINGS__BASE_URL: http://ui.aidaui.lvh.me:3000/
    stdin_open: true
    depends_on:
      - redis

  webpack:
    <<: *base
    ports:
      - "3035:3035"
    command: /bin/sh -c './bin/yarn install && bundle exec ./bin/webpack-dev-server'

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:4

  backend:
    image: instedd/aida:dev
    ports:
      - "4000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: ecto://root:@db/aida-backend
    command: /bin/sh -c 'mix ecto.migrate && mix phx.server'

volumes:
  db:
  bundle:
  node_modules:
